export const FETCH_NOTES = "FETCH_NOTES";

export const MY_NOTES_FETCH_SUCCESSFULL = "MY_NOTES_FETCH_SUCCESSFULL";
export const MY_NOTES_FETCH_STARTED = "MY_NOTES_FETCH_STARTED";
export const MY_NOTES_FETCH_FAILED = "MY_NOTES_FETCH_FAILED";

export const ADD_NOTES_COMPLETED = "ADD_NOTES_COMPLETED";
export const ADD_NOTES_STARTED = "ADD_NOTES_STARTED";
export const ADD_NOTES_ERROR = "ADD_NOTES_ERROR";

export const SEARCH_STARTED = "SEARCH_STARTED";
export const SEARCH_ENDED = "SEARCH_ENDED";
export const SEARCH_ERROR = "SEARCH_ERROR";

export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";

export const LOGIN_START = "LOGIN_START";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGIN_SUCCESSFULL = "LOGIN_SUCCESSFULL";
export const LOGOUT_SUCCESSFULL = "LOGOUT_SUCCESSFULL";

export const SIGNUP_START = "SIGNUP_START";
export const SIGNUP_SUCCESSFULL = "SIGNUP_SUCCESSFULL";
export const SIGNUP_ERROR = "SIGNUP_ERROR";

export const AUTHENTICATION_ERROR = "AUTHENTICATION_ERROR";
export const AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED";

export const BOOKMARK_START = "BOOKMARK_START";
export const BOOKMARK_SUCCESS = "BOOKMARK_SUCCESS";
export const BOOKMARK_ERROR = "BOOKMARK_ERROR";

export const BOOKMARK_REMOVE_START = "BOOKMARK_REMOVE_START";
export const BOOKMARK_REMOVE_SUCCESS = "BOOKMARK_REMOVE_SUCCESS";
export const BOOKMARK_REMOVE_ERROR = "BOOKMARK_REMOVE_ERROR";

export const FETCH_BOOKMARK_STARTED = "FETCH_BOOKMARK_STARTED";
export const FETCH_BOOKMARK_SUCCESSFULL = "FETCH_BOOKMARK_SUCCESSFULL";
export const FETCH_BOOKMARK_ERROR = "FETCH_BOOKMARK_ERROR";

export const FETCH_PRIVATE_NOTES_START = "FETCH_PRIVATE_NOTES";
export const FETCH_PRIVATE_NOTES_SUCCESS = "FETCH_PRIVATE_NOTES_SUCCESS";
export const FETCH_PRIVATE_NOTES_ERROR = "FETCH_PRIVATE_NOTES_ERROR";

export const FULL_NOTE_FETCH_START = "FULL_NOTE_FETCH_START";
export const FULL_NOTE_FETCH_COMPLETED = "FULL_NOTE_FETCH_COMPLETED";
export const FULL_NOTE_FETCH_ERROR = "FULL_NOTE_FETCH_ERROR";
export const EDIT_NOTE_FETCH_START = "EDIT_NOTE_FETCH_START";
export const EDIT_NOTE_FETCH_COMPLETED = "EDIT_NOTE_FETCH_COMPLETED";
export const EDIT_NOTE_FETCH_ERROR = "EDIT_NOTE_FETCH_ERROR";
export const REMOVE_NOTE_FETCH_START = "REMOVE_NOTE_FETCH_START";
export const REMOVE_NOTE_FETCH_COMPLETED = "REMOVE_NOTE_FETCH_COMPLETED";
export const REMOVE_NOTE_FETCH_ERROR = "REMOVE_NOTE_FETCH_ERROR";
export const UNDO_REMOVE_NOTE_FETCH_START = "UNDO_REMOVE_NOTE_FETCH_START";
export const UNDO_REMOVE_NOTE_FETCH_COMPLETED =
  "UNDO_REMOVE_NOTE_FETCH_COMPLETED";
export const UNDO_REMOVE_NOTE_FETCH_ERROR = "UNDO_REMOVE_NOTE_FETCH_ERROR";
